<?php

namespace App\Support;

/** Canonical mutate ops from WP class-dashboard-admin-mutations.php (§15).
 *  165 active ops (P0-3 telegram mirror + P1 marketing/UI groups/repair + P0-2 configs; link_wp_user + reseller_bot_secret_rotate removed v29). */
class MutateOpCatalog
{
    /** @return list<string> */
    public static function deprecated(): array
    {
        return [];
    }

    /** @return list<string> */
    public static function all(): array
    {
        return array (
  0 => 'bot_admin_id_add',
  1 => 'bot_admin_id_remove',
  2 => 'bot_delete_webhook',
  3 => 'bot_diagnostics',
  4 => 'bot_reseller_delete',
  5 => 'bot_reseller_save',
  6 => 'bot_reseller_secret_rotate',
  7 => 'bot_reseller_toggle_enabled',
  8 => 'bot_set_webhook',
  9 => 'bot_set_update_mode',
  10 => 'bot_test_bale',
  11 => 'bot_test_telegram',
  12 => 'bot_toggle_enabled',
  13 => 'bot_toggle_platform_enabled',
  14 => 'bot_ui_layout_reset',
  15 => 'bot_ui_layout_save',
  16 => 'bot_ui_group_create',
  17 => 'bot_ui_group_delete',
  18 => 'broadcast_cancel',
  19 => 'broadcast_run_worker',
  20 => 'broadcast_send',
  21 => 'card_add',
  22 => 'card_delete',
  23 => 'card_reorder',
  24 => 'card_update',
  25 => 'configs_assign_plan',
  26 => 'configs_client_delete',
  27 => 'configs_client_reset_traffic',
  28 => 'configs_client_toggle_enable',
  29 => 'configs_clients_batch',
  30 => 'configs_delete_expired_linked',
  31 => 'configs_panel_client_patch',
  32 => 'crypto_settings',
  33 => 'rial_settings',
  34 => 'discount_delete',
  35 => 'discount_redemptions',
  36 => 'discount_save',
  37 => 'force_join_publish',
  38 => 'inbound_autolink',
  39 => 'inbound_link',
  40 => 'l2tp_add',
  41 => 'l2tp_delete',
  42 => 'l2tp_update',
  43 => 'logs_clear',
  44 => 'marketing_lifecycle_confirm_defaults',
  45 => 'marketing_preview_message',
  46 => 'marketing_rule_delete',
  47 => 'marketing_rule_save',
  48 => 'marketing_run_rule_now',
  49 => 'marketing_send_manual',
  50 => 'membership',
  51 => 'panel_economics_mark_paid',
  52 => 'panel_economics_save',
  53 => 'panel_test',
  54 => 'panel_xp',
  55 => 'plan',
  56 => 'plan_category',
  57 => 'purge_expired_purge_one',
  58 => 'purge_expired_purge_ready',
  59 => 'purge_expired_run_cron',
  60 => 'receipt_action',
  61 => 'receipt_reject_reasons_save',
  62 => 'receipt_set_status',
  63 => 'receipt_update',
  64 => 'reseller_backfill_run',
  65 => 'reseller_bind_users',
  66 => 'reseller_bot_tokens_save',
  67 => 'reseller_bot_webhook_delete',
  68 => 'reseller_bot_webhook_set',
  69 => 'reseller_inbound_labels_save',
  70 => 'reseller_panel_prices_save',
  71 => 'reseller_payment_methods_save',
  72 => 'reseller_permissions_save',
  73 => 'reseller_wallet_topup_checkout',
  74 => 'reseller_wholesale_lines_assign',
  75 => 'reseller_dashboard_provision',
  76 => 'service_alerts_patch',
  77 => 'service_apply_canonical_panel_identity',
  78 => 'service_delete',
  79 => 'service_panel_delete_client',
  80 => 'service_panel_refresh',
  81 => 'service_panel_sync',
  82 => 'service_panel_transfer',
  83 => 'service_regen_key',
  84 => 'service_regen_sub_id',
  85 => 'service_set_limit_ip',
  86 => 'service_set_note',
  87 => 'settings_tab',
  88 => 'shared_economics_save',
  89 => 'telegram_mirror_delete',
  90 => 'telegram_mirror_delete_webhook',
  91 => 'telegram_mirror_diagnostics',
  92 => 'telegram_mirror_save',
  93 => 'telegram_mirror_set_webhook',
  94 => 'telegram_mirror_test',
  95 => 'telegram_mirror_toggle',
  96 => 'telegram_proxy_test',
  97 => 'telegram_relay_admin_dashboard',
  98 => 'telegram_relay_admin_doctor',
  99 => 'telegram_relay_admin_domain_add',
  100 => 'telegram_relay_admin_domain_remove',
  101 => 'telegram_relay_admin_job',
  102 => 'telegram_relay_admin_logs',
  103 => 'telegram_relay_admin_nginx_reload',
  104 => 'telegram_relay_admin_nginx_render',
  105 => 'telegram_relay_admin_nginx_test',
  106 => 'telegram_relay_admin_service_restart',
  107 => 'telegram_relay_admin_ssl_issue',
  108 => 'telegram_relay_admin_ssl_renew',
  109 => 'telegram_relay_admin_ssl_status',
  110 => 'telegram_relay_admin_update',
  111 => 'telegram_relay_auto_sync',
  112 => 'telegram_relay_domains_sync',
  113 => 'telegram_relay_rotate_secret',
  114 => 'telegram_relay_set_webhook',
  115 => 'telegram_relay_set_webhook_reseller',
  116 => 'telegram_relay_status',
  117 => 'telegram_relay_sync',
  118 => 'telegram_relay_test',
  119 => 'text_reset_one',
  120 => 'texts_reset',
  121 => 'texts_save',
  122 => 'unit_economics_config_save',
  123 => 'unit_economics_save',
  124 => 'user_add_days',
  125 => 'user_add_volume',
  126 => 'user_admin_message',
  127 => 'user_balance_delta',
  128 => 'user_create_service',
  129 => 'user_manual_create',
  130 => 'user_merge',
  131 => 'user_merge_preview',
  132 => 'user_reduce_days',
  133 => 'user_reduce_volume',
  134 => 'user_renew_service',
  135 => 'user_service_add_slots',
  136 => 'user_service_reduce_slots',
  137 => 'user_service_toggle_enable',
  138 => 'user_service_transfer',
  139 => 'user_set_referrer',
  140 => 'user_set_role',
  141 => 'user_status',
  142 => 'users_bulk_alerts',
  143 => 'users_bulk_extend',
  144 => 'users_bulk_job_cancel',
  145 => 'users_bulk_job_resume',
  146 => 'users_bulk_run_worker',
  147 => 'users_bulk_slots',
  148 => 'users_bulk_volume',
  149 => 'users_bulk_wallet',
  150 => 'wholesale_line_delete',
  151 => 'wholesale_line_save',
  152 => 'panel_merge_preview',
  153 => 'panel_merge_execute',
  154 => 'configs_panel_del_orphans',
  155 => 'panels_repair_identities',
  156 => 'configs_bulk_reset_traffic',
  157 => 'configs_client_clear_ips',
  158 => 'configs_client_fetch_ips',
  159 => 'configs_client_set_inbounds',
  160 => 'configs_clients_bulk_set_inbounds',
  161 => 'configs_delete_expired_older_than',
  162 => 'configs_inbound_patch',
  163 => 'configs_panel_del_depleted',
  164 => 'configs_reset_all_panel_traffic',
);
    }
}
