# MeowVPN — Dashboard Core (Laravel API)
# Generated by backend/scripts/ops/install — do not edit by hand.

upstream meowvpn_core_upstream {
    server 127.0.0.1:8080;
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name {{SERVER_NAME}};

    client_max_body_size 32m;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

{{HTTP_REDIRECT_OR_PROXY}}
}

{{SSL_SERVER_BLOCK}}
