# MeowVPN — Dashboard Frontend (React SPA)
# Generated by backend/scripts/ops/install

upstream meowvpn_dashboard_upstream {
    server 127.0.0.1:3001;
    keepalive 8;
}

server {
    listen 80;
    listen [::]:80;
    server_name {{SERVER_NAME}};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

{{HTTP_REDIRECT_OR_PROXY}}
}

{{SSL_SERVER_BLOCK}}
