# MeowVPN — Telegram relay (docker on 127.0.0.1:8787)
# Generated by backend/scripts/ops/install

upstream meowvpn_relay_upstream {
    server 127.0.0.1:8787;
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name {{SERVER_NAME}};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

{{HTTP_REDIRECT_OR_PROXY}}
}

{{SSL_SERVER_BLOCK}}
