<?php

namespace App\Services\AdminState;

class PayloadDefaults
{
    /** @return array<string, mixed> */
    public static function root(): array
    {
        return [
            'settings' => [],
            'paymentMethods' => null,
            'textDefaults' => [],
            'uiLayout' => ['version' => 0, 'surfaces' => []],
            'uiRegistry' => ['version' => 0, 'surfaces' => []],
            'referralStats' => null,
            'referralEvents' => [],
            'resellerReportsStats' => null,
            'resellerReports' => [],
            'resellerReportsRows' => [],
            'resellerReportsDaily' => [],
            'marketingLifecycleStats' => null,
            'marketingLifecycleFunnel' => [],
            'marketingFunnel' => [],
            'marketingRules' => [],
            'marketingRuleStats' => [],
            'marketingOffers' => [],
            'marketingSkipBreakdown' => [],
            'marketingSegmentTrend' => [],
            'marketingSegmentTrend' => [],
            'panels' => [],
            'plans' => [],
            'planCategories' => [],
            'panelTemplates' => [],
            'panelTemplatesMeta' => null,
            'cards' => [],
            'l2tpServers' => [],
            'texts' => [],
            'discountCodes' => [],
            'discountUsageSummary' => [
                'total_redemptions' => 0,
                'total_discount_toman' => 0.0,
                'active_codes' => 0,
            ],
            'pendingUsers' => [],
            'usersList' => [],
            'resellers' => [],
            'resellerPermissionsMap' => [],
            'resellerPanelPricesMap' => [],
            'resellerBotMap' => [],
            'wholesaleCatalogByPanel' => [],
            'wholesaleLinesCatalog' => [],
            'wholesaleLines' => [],
            'resellerWholesaleLineIdsMap' => [],
            'botsList' => [],
            'telegramMirrorsList' => [],
            'payments' => [],
            'paymentAggregates' => [],
            'receipts' => [],
            'receiptAggregates' => [],
            'orders' => [],
            'orderAggregates' => [],
            'paymentsView' => 'receipts',
            'broadcasts' => [],
            'broadcastQueueAggregates' => [],
            'navTabs' => [],
            'overview' => [],
            'monitorHosts' => [],
            'unitEconomics' => null,
            'panelEconomicsMap' => null,
            'panelFinancialReports' => null,
            'resellerOverviewMetrics' => null,
        ];
    }
}
